# Generated by Django 5.0.3 on 2024-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spieler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('titel', models.IntegerField(default=0)),
                ('auto', models.CharField(max_length=100)),
                ('punkte', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spieltage', models.IntegerField(default=0)),
                ('spieler', models.ManyToManyField(to='myapp.spieler')),
            ],
        ),
    ]
