# Generated by Django 5.0.3 on 2024-03-30 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fisch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laenge', models.IntegerField(default=0)),
                ('ort', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fischart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Angler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fische', models.ManyToManyField(related_name='angler_fische', to='myapp.fisch')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angler_rekord', to='myapp.fisch')),
            ],
        ),
        migrations.AddField(
            model_name='fisch',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fische', to='myapp.fischart'),
        ),
        migrations.CreateModel(
            name='Rekord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekords', to='myapp.angler')),
                ('fisch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fisch')),
            ],
        ),
    ]
