# Generated by Django 5.0.3 on 2024-03-30 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fisch_fischart_angler_fisch_name_rekord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angler',
            name='rekord',
        ),
        migrations.AddField(
            model_name='fisch',
            name='fischart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fische', to='myapp.fischart'),
        ),
        migrations.AlterField(
            model_name='angler',
            name='fische',
            field=models.ManyToManyField(blank=True, related_name='angler', to='myapp.fisch'),
        ),
        migrations.AlterField(
            model_name='fisch',
            name='laenge',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fisch',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
