# Generated by Django 5.0.3 on 2024-04-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_angler_rekord_fisch_fischart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='angler',
            name='koeder',
            field=models.IntegerField(default=0),
        ),
    ]
